###
GET http://localhost:4000/api/users
###
POST http://localhost:4000/api/users
content-Type: application/json

{
    "username": "nike32",
    "email": "nike32@gmail.com",
    "password": "9101112",
    "role": "store"
} 
###
DELETE http://localhost:4000/api/users/6060a99a01771e3aa86b105c
###
PUT http://localhost:4000/api/users/6060a99a01771e3aa86b105c
content-Type: application/json

{
    "username": "ex1",
    "password": "expsswd",
    "name": "example",
    "lastname": "fullexample"
} 
###
GET http://localhost:4000/api/users/6060a99a01771e3aa86b105c