###
GET http://localhost:4000/api/sedes
###
POST http://localhost:4000/api/sedes
content-Type: application/json

{
    "nombre": "Hospital Exemple",
    "localizacion": "14.1120700, 20.3511100",
    "poblacion": "Població Exemple"
} 
###
DELETE http://localhost:4000/api/sedes/6082aa9eacd28a3394add378
###
PUT http://localhost:4000/api/sedes/6082a98bacd28a3394add377
content-Type: application/json

{
    "nombre": "Hospital Clinic",
    "localizacion": "30.1120700, 40.3511100",
    "poblacion": "Barcelona"
} 
###
GET http://localhost:4000/api/sedes/6082a98bacd28a3394add377